config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"

  get "/", to: "home#index"
  get "/home/secret"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create] do
    resources :collections, only: [:index]
    resources :col_sets, path: '/collections/sets'
  end

  resources :lego
  resources :sets


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/col_set.rb
class ColSet < ApplicationRecord
  belongs_to :user
  default_scope { order(favorite: :asc)}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :col_set

    validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
    end
end

app/controllers/col_sets_controller.rb
class ColSetsController < ApplicationController
  include Parse

  def index
    if current_user.blank?
      redirect_to root_path
    end
    user = User.find(current_user.id)
    @sets = user.col_set
  end

  def show
    if current_user.blank?
      redirect_to root_path
    end
    @user = User.find(current_user.id)
    @set = @user.col_set.find(params[:id])
    @theme = parse_theme(@set['theme_id'])
  end

  def create
    @user = User.find(current_user.id)
    @set = @user.col_set.create(col_set_params)
    redirect_to user_col_sets_path
  end

  def update
    @user = User.find(current_user.id)
    @set = @user.col_set.find(params[:id])
    @set.update(favorite_params)
    redirect_to user_col_set_path(params[:id])
  end

  def destroy
    @user = User.find(current_user.id)
    @set = @user.col_set.find(params[:id])
    @set.destroy
    redirect_to user_col_sets_path
  end

  private
    def col_set_params
      params.require(:col_set).permit(:set_num, :name, :year, :theme_id, :num_parts, :set_img_url, :set_url)
    end
  
  private
    def favorite_params
      params.require(:col_set).permit(:favorite)
    end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    if current_user.blank?
      redirect_to root_path
    end

    @user = User.find(params[:user_id])
    @set = @user.col_set.first
  end
end

app/controllers/concerns/Parse.rb
module Parse
    extend ActiveSupport::Concern
    def api_key
        key = ENV['API_KEY']
    end

    def base_uri
        uri = 'https://rebrickable.com/api/v3/lego'
    end

    def parse_theme (theme_id)
        response = RestClient.get("#{base_uri}/themes/#{theme_id}/?key=#{api_key}", {accept: :json})
        data = JSON.parse(response.body)
        theme = data['name']
    end

    def parse_set (set_id)
        response = RestClient.get("#{base_uri}/sets/#{set_id}/?key=#{api_key}", {accept: :json})
        data = JSON.parse(response.body)
    end

    def parse_sets (page, min_year, max_year, min_parts, max_parts)
        api_uri = "#{base_uri}/sets/?key=#{api_key}&page=#{page}&page_size=16&ordering=year&min_year=#{min_year}&max_year=#{max_year}&min_parts=#{min_parts}&max_parts=#{max_parts}"
        puts api_uri
        response = RestClient.get(api_uri)
        data = JSON.parse(response.body)
    end
end

app/controllers/concerns/SearchData.rb
module SearchData
    extend ActiveSupport::Concern

    def part_count
        parts = [0,500,1000,1500,2000,2500,3000,4000]
    end

    def year_count
        years = []
        for a in 1949..2024 do
            years.push(a)
        end
        return years
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lego_controller.rb
class LegoController < ApplicationController
  include Parse

  def show
    @data = parse_set(params[:id])
    @theme = parse_theme(@data['theme_id'])
    @user = current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Login failed"
      redirect_to new_session_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/sets_controller.rb
class SetsController < ApplicationController
  include SearchData
  include Parse

  def index
    @years = year_count
    @parts = part_count
  end

  def show
    @years = year_count
    @parts = part_count
    @data = parse_sets(params[:id].to_i, params[:min_year], params[:max_year], params[:min_parts], params[:max_parts])
    puts ("Next=#{@data['next']}")
    puts ("Previous=#{@data['previous']}")
    @previous = params[:id].to_i - 1
    @next = params[:id].to_i + 1
    @params = params
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save 
      redirect_to new_session_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/col_sets_helper.rb
module ColSetsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/collections_sets_helper.rb
module CollectionsSetsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lego_helper.rb
module LegoHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sets_helper.rb
module SetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-info sticky-top">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <% if current_user %>
                    <%= link_to "Collections", user_collections_path(current_user), class: "nav-link" %>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to "Sets Catalog", sets_path, class: "nav-link" %>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <%= link_to "Collect-a-Brick", root_path, class: "navbar-brand mx-auto" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ms-auto">
            <% if current_user %>
                <li class="nav-item">
                    <%= link_to "Sign Out", session_path(current_user), data: {turbo_method: :delete}, class: "nav-link" %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to 'Login', new_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign Up', new_user_path, class: "nav-link" %>
                </li>
            <% end %>
        <ul>
    </div>
</nav>

app/views/col_sets/index.html.erb
<%= render "application/nav" %>

<h1>Sets</h1>
<div class="d-flex flex-row flex-wrap justify-content-start container-fluid">
    <% for set in @sets %>
        <button type="button" class="btn bg-light bg-gradient btn-outline-secondary m-2 shadow btn-primary">
            <%= link_to user_col_set_path(current_user, set['id']), class: "text-decoration-none text-reset" do%>
                <%= render "sets/card", set: set%>
            <% end %>
        </button>
    <% end %>
</div>

app/views/col_sets/show.html.erb
<%= render "application/nav" %>

<div class="d-flex flex-column justify-content-center">
    <%= render "lego/info", data:@set%>
    <div class="container-fluid d-flex justify-content-center align-items-center gap-3">
        <%= form_with model: [ @user, @set ] do |form| %>
            <p>
                <%= form.hidden_field :favorite, value: !@set['favorite'] %>
            </p>
            <% if @set['favorite']%>
                <p>
                    <%= form.submit "Unfavorite", class: "btn btn-warning"%>
                </p>
            <% else %>
                <p>
                    <%= form.submit "Favorite", class: "btn btn-success"%>
                </p>
            <% end %>
        <% end %>
        <%= link_to "Remove", user_col_set_path(@set), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        }, class: "btn btn-danger " %>
    </div>

    <%= link_to "Back to Sets", user_col_sets_path, class:"btn btn-outline-dark me-auto"%>
</div>

app/views/collections/index.html.erb
<%= render "application/nav" %>

<h1><%= current_user.name %>'s Collections</h1>

<% if @set%>
<div class="d-flex flex-row flex-wrap justify-content-center container-fluid">
    <button type="button" class="btn bg-light bg-gradient btn-outline-secondary m-2 shadow btn-primary">
        <%= link_to user_col_sets_path, class: "text-decoration-none text-muted" do%>
            <div class="card" style="height: 250px; width: 250px;">
                <div class="card-body">
                    <h5>Sets Collection</h5>
                    <img src=<%= @set['set_img_url']%> alt= <%=@set['name'] %> class="img-fluid" style="height: 150px; width: auto;"/>
                </div>
            </div>
        <% end %>
    </button>
</div>
<% else %>
    <div class="container-fluid text-center">
        <h1>No sets in your collection!</h1>
        <%= link_to "To Sets", sets_path, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/home/index.html.erb
<%= render "application/nav" %>

<div class="justify-content-center text-center">
<% if current_user %>
  <h1>Welcome <%= current_user.name %>, to Collect-a-Brick!</h1>
<% else %>
  <h1>Welcome to Collect-a-Brick!</h1>
  <p><%= link_to 'Login', new_session_path %> is required to save sets to your collection.</p>
<% end %>
</div>

app/views/lego/_info.html.erb
<div class="card-body">
    <%if data['favorite'] == true %><span class='text-info'><% end %>
    <h1><%= data['name'] %> (<%= data['set_num'] %>)</h1>
    <%if data['favorite'] == true %></span><% end %>
</div>
<div class="align-self-center justify-content-center m-4" style="max-width: 500px">
    <img src=<%= data['set_img_url']%> alt= <%= data['name'] %> class="card-img img-fluid"/>
</div>
<div class="container justify-content-center">
    <div class="d-flex row justify-content-center align-items-stretch align-items-center">
        <div class="col-auto border">
            <div class="fw-bold text-center">Number of Parts:</div>
            <div class="text-center"><%= data['num_parts']%></div>
        </div>
        <div class="col-auto border">
            <div class="fw-bold text-center">Theme:</div>
            <div class="text-center"><%= @theme %></div>
        </div>
        <div class="col-auto border">
            <div class="fw-bold text-center">Year:</div>
            <div class="text-center"><%= data['year'] %></div>
        </div>
        <div class="col-auto border">
            <%= link_to "More Info", data['set_url'], target: :_blank, class:"btn btn-info"%>
        </div>
    </div>
</div>

app/views/lego/show.html.erb
<%= render "application/nav" %>

<div class="d-flex flex-column justify-content-center text-center">
    <%= render "lego/info", data:@data%>
    
    <% if current_user %>
        <%= form_with model: [ @user, @user.col_set.build ], class:" text-center" do |form| %>
            <p>
                <%= form.hidden_field :set_num, value: @data['set_num'] %>
                <%= form.hidden_field :name, value: @data['name'] %>
                <%= form.hidden_field :year, value: @data['year'] %>
                <%= form.hidden_field :theme_id, value: @data['theme_id'] %>
                <%= form.hidden_field :num_parts, value: @data['num_parts'] %>
                <%= form.hidden_field :set_img_url, value: @data['set_img_url'] %>
                <%= form.hidden_field :set_url, value: @data['set_url'] %>
            </p>
            <p>
                <%= form.submit "Add to your collection!", class: "btn btn-primary"%>
            </p>
        <% end %><br>
    <% else %>
        <div class="bg-light mx-auto d-flex text-danger m-3 p-2 fw-bold">Login to add to collection!</div>
    <% end %>
    <div class=""></div>
</div>

app/views/sets/_card.html.erb
<div class="card" style="height: 250px; width: 250px;">
    <div class="card-body">
        <%if set['favorite'] == true %><span class='text-info'><% end %>
            <h5><%= set['name'] %> (<%= set['set_num'] %>)</h5>
        <%if set['favorite'] == true %></span><% end %>
        <img src=<%= set['set_img_url']%> alt= <%=set['name'] %> class="img-fluid" style="height: 150px; width: auto;"/>
    </div>
</div>

app/views/sets/_search.html.erb
<nav class="navbar navbar-dark bg-secondary ">
    <div class="container-fluid justify-content-around ">
        <form action=<%=set_path(1)%>% class="d-flex flex-wrap input-control gap-3 justify-content-center">
            <select name="min_year" class="form-select" style="width: 150px">
                <option value=<%= nil %>>Min Year</option>
                <% for year in years do %>
                    <option value=<%= year %>><%= year %></option>
                <% end %>
            </select>
            <select name="max_year" class="form-select" style="width: 150px">
                <option value=<%= nil %>>Max Year</option>
                <% for year in years do %>
                    <option value=<%= year %>><%= year %></option>
                <% end %>
            </select>
            <select name="min_parts" class="form-select" style="width: 150px">
                <option value=<%= nil %>>Min Parts</option>
                <% for part in parts do %>
                    <option value=<%= part %>><%= part %></option>
                <% end %>
            </select>
            <select name="max_parts" class="form-select" style="width: 150px">
                <option value=<%= nil %>>Max Parts</option>
                <% for part in parts do %>
                    <option value=<%= part %>><%= part %></option>
                <% end %>
            </select>
            <input type="submit" value="Search" class="btn btn-primary">
        </form>
    </div>
</nav>

app/views/sets/index.html.erb
<%= render "application/nav" %>

<div class="text-center bg-secondary text-light">
    <h1>Search for a set!</h1>
    <h4>(Params optional)</h4>

<%= render "sets/search", years: @years, parts: @parts%>
</div>

app/views/sets/show.html.erb
<%= render "application/nav" %>

<%= render "sets/search", years: @years, parts: @parts%>

<nav class="navbar bg-light">
    <% if @data["previous"] != nil%>
        <div class="justify-content-start me-auto">
            <%= link_to "Previous Page", set_path(@previous, min_year: @params[:min_year], max_year: @params[:max_year], min_parts: @params[:min_parts], max_parts: @params[:max_parts]), class: "btn btn-outline-dark"%>
        </div>
    <% end %>
    <% if @data["next"] != nil%>
        <div class="justify-content-end ms-auto">
            <%= link_to "Next Page", set_path(@next, min_year: @params[:min_year], max_year: @params[:max_year], min_parts: @params[:min_parts], max_parts: @params[:max_parts]), class: "btn btn-outline-dark"%>
        </div>
    <% end %>
</nav>

<div class="justify-content-center">
    <div class="d-flex flex-row flex-wrap justify-content-center container-fluid">
        <% for set in @data['results'] %>
            <button type="button" class="btn bg-light bg-gradient btn-outline-secondary m-2 shadow btn-primary">
                <%= link_to lego_path(set['set_num']), class: "text-decoration-none text-muted" do%>
                    <%= render "sets/card", set: set %>
                <% end %>
            </button>
        <% end %>
    </div>
</div>

<nav class="navbar bg-light">
    <% if @data["previous"] != nil%>
        <div class="justify-content-start me-auto">
            <%= link_to "Previous Page", set_path(@previous, min_year: @params[:min_year], max_year: @params[:max_year], min_parts: @params[:min_parts], max_parts: @params[:max_parts]), class: "btn btn-outline-dark"%>
        </div>
    <% end %>
    <% if @data["next"] != nil%>
        <div class="justify-content-end ms-auto">
            <%= link_to "Next Page", set_path(@next, min_year: @params[:min_year], max_year: @params[:max_year], min_parts: @params[:min_parts], max_parts: @params[:max_parts]), class: "btn btn-outline-dark"%>
        </div>
    <% end %>
</nav>

app/views/users/new.html.erb
<%= render "application/nav" %>
<h1>Sign Up</h1>
<%= form_with model: @user do |f| %>
  <div class="container">
    <div class="row g-3">
      <div class="col-md-6">
      <%= f.label :name, class: "form-label"  %><br>
      <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="row g-3">
      <div class="col-md-6">
      <%= f.label :password, class: "form-label"  %><br>
      <%= f.password_field :password, class: "form-control" %>
      </div>
    </div>
    <div class="row g-3">
      <div class="col-md-6">
      <%= f.label :password_confirmation, class: "form-label"  %><br>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
    <% if @user.errors.any? %>
      <div class="row g-3">
        <div class="alert alert-warning col-md-3">
          <% @user.errors.full_messages.each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="row g-3">
      <div class="col-md-1">
        <%= f.submit "Sign Up", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>